const path = require("path");

function loadListFile(filename) {
  /* We must load in the list to be processed before downloading */
  return new Promise(resolve => {
    const wikiList = [];
    const lineReader = require("readline").createInterface({
      input: require("fs").createReadStream(
        path.join(__dirname, "selections", filename)
      )
    });

    lineReader.on("line", line => wikiList.push(line));
    lineReader.on("close", () => resolve(wikiList));
  });
}

const cleanListOfLinks = linkArr => {
  let linkList = linkArr;
  linkList = linkList.filter(url => {
    if (!url) return false;
    else if (url[0] === "#") return false;
    else if (/https?:\/\/.+wiki/g.test(url)) return true;
    else if (/https?:\/\//g.test(url)) return false;
    else if (/index.php/g.test(url)) return false;
    else if (/action=edit/g.test(url)) return false;
    else if (/^\/\//.test(url)) return false;
    return true;
    // else if (/File:/g.test(url)) return false; // Removes potential pictures see: https://en.wikipedia.org/wiki/ASCII
  });
  linkList = linkList.map(url => decodeURI(url));
  linkList = linkList.map(url => url.replace(/^\/wiki\//, ""));
  linkList = linkList.map(url => url.split("?")[0]); // get rid of parameters eg: ?action=submit
  return linkList;
};

const cleanUrl = url => (url[0] === "/" ? url.slice(2) : url);
const getFilename = url => url.split("/").slice(-1)[0].replace(/%/g, "");

const cssIds = {
  bodyContent: "a",
  "ca-watch": "b",
  catlinks: "c",
  "column-content": "d",
  content: "e",
  contentSub2: "f",
  "editpage-specialchars": "g",
  firstHeading: "h",
  footer: "i",
  "footer-icons": "j",
  "footer-places": "k",
  globalWrapper: "l",
  "jump-to-nav": "m",
  "left-navigation": "n",
  localNotice: "o",
  mw_content: "p",
  "mw-head": "q",
  "mw-head-base": "r",
  "mw-page-base": "s",
  "mw-panel": "t",
  "mw-prefixindex-nav-table": "u",
  "mw-revision-nav": "v",
  "mw-searchButton": "w",
  "mw-userjspreview": "x",
  "p-lang": "y",
  "p-logo": "z",
  "p-personal": "aa",
  "p-search": "ab",
  privacy: "ac",
  "pt-anonuserpage": "ad",
  "right-navigation": "ae",
  searchButton: "af",
  searchInput: "ag",
  simpleSearch: "ah",
  siteNotice: "ai",
  siteSub: "aj",
  wpTextbox1: "ak"
};

const cssClasses = {
  icon: "a",
  body: "b",
  column: "c",
  columns: "d",
  center: "e",
  menu: "f",
  navbar: "g",
  navbox: "h",
  NavContent: "i",
  NavEnd: "j",
  NavFrame: "k",
  NavHead: "l",
  "action-view": "m",
  ambox: "n",
  "ambox-content": "o",
  "ambox-delete": "p",
  "ambox-move": "q",
  "ambox-notice": "r",
  "ambox-protection": "s",
  "ambox-speedy": "t",
  "ambox-style": "u",
  autocomment: "v",
  autonumber: "w",
  bordered: "x",
  botedit: "y",
  brokenref: "z",
  catlinks: "aa",
  "catlinks-allhidden": "ab",
  "check-icon": "ac",
  citation: "ad",
  cleanup: "ae",
  cmbox: "af",
  "cmbox-content": "ag",
  "cmbox-delete": "ah",
  "cmbox-move": "ai",
  "cmbox-notice": "aj",
  "cmbox-protection": "ak",
  "cmbox-speedy": "al",
  "cmbox-style": "am",
  "columns-2": "an",
  "columns-3": "ao",
  "columns-4": "ap",
  "columns-5": "aq",
  comment: "ar",
  "compact-ambox": "as",
  dmbox: "at",
  editOptions: "au",
  emptyPortlet: "av",
  error: "aw",
  errorbox: "ax",
  external: "ay",
  firstHeading: "az",
  flaggedrevs_short: "ba",
  floatleft: "bb",
  floatright: "bc",
  fmbox: "bd",
  "fmbox-editnotice": "be",
  "fmbox-system": "bf",
  "fmbox-warning": "bg",
  free: "bh",
  gallerybox: "bi",
  geography: "bj",
  hatnote: "bk",
  "hide-when-compact": "bl",
  "history-deleted": "bm",
  hlist: "bn",
  imbox: "bo",
  "imbox-content": "bp",
  "imbox-delete": "bq",
  "imbox-featured": "br",
  "imbox-license": "bs",
  "imbox-move": "bt",
  "imbox-notice": "bu",
  "imbox-protection": "bv",
  "imbox-speedy": "bw",
  "imbox-style": "bx",
  infobox: "by",
  "inputbox-hidecheckboxes": "bz",
  "k-attribution": "ca",
  "k-player": "cb",
  lastline: "cc",
  letterhead: "cd",
  listenlist: "ce",
  loading: "cf",
  "locked-warning": "cg",
  ltr: "ch",
  magnify: "ci",
  "mbox-empty-cell": "cj",
  "mbox-image": "ck",
  "mbox-imageright": "cl",
  "mbox-inside": "cm",
  "mbox-small": "cn",
  "mbox-small-left": "co",
  "mbox-text": "cp",
  "mbox-text-span": "cq",
  medialist: "cr",
  mediawiki: "cs",
  menuForceShow: "ct",
  merge: "cu",
  messagebox: "cv",
  mw_metadata: "cw",
  "mw-ajax-loader": "cx",
  "mw-body": "cy",
  "mw-body-content": "cz",
  "mw-cite-backlink": "da",
  "mw-code": "db",
  "mw-collapsed": "dc",
  "mw-collapsible-content": "dd",
  "mw-collapsible-leftside-toggle": "de",
  "mw-collapsible-toggle": "df",
  "mw-content-ltr": "dg",
  "mw-content-rtl": "dh",
  "mw-datatable": "di",
  "mw-delete-editreasons": "dj",
  "mw-editfont-monospace": "dk",
  "mw-editfont-sans-serif": "dl",
  "mw-editfont-serif": "dm",
  "mw-editsection": "dn",
  "mw-editsection-like": "do",
  "mw-editsection-visualeditor": "dp",
  "mw-empty-elt": "dq",
  "mw-empty-li": "dr",
  "mw-hidden-cats-hidden": "ds",
  "mw-hide-empty-elt": "dt",
  "mw-indicator": "du",
  "mw-indicators": "dv",
  "mw-infobox": "dw",
  "mw-infobox-left": "dx",
  "mw-infobox-right": "dy",
  "mw-input": "dz",
  "mw-input-with-label": "ea",
  "mw-label": "eb",
  "mw-parser-output": "ec",
  "mw-redirect": "ed",
  "mw-revdel-checkbox": "ee",
  "mw-revdelundel-hidden": "ef",
  "mw-revdelundel-link": "eg",
  "mw-selflink": "eh",
  "mw-small-spinner": "ei",
  "mw-submit": "ej",
  "mw-ui-checkbox": "ek",
  "mw-userlink": "el",
  "mw-warning": "em",
  "mw-warning-with-logexcerpt": "en",
  "mw-wiki-logo": "eo",
  "mwe-math-element": "ep",
  "mwe-math-mathml-inline": "eq",
  "navbox-abovebelow": "er",
  "navbox-group": "es",
  "navbox-list": "et",
  "navbox-subgroup": "eu",
  "navbox-title": "ev",
  NavPic: "ew",
  NavToggle: "ex",
  nested: "ey",
  "nested-talk": "ez",
  new: "fa",
  noarticletext: "fb",
  nonumtoc: "fc",
  "not-patrolled": "fd",
  nowraplinks: "fe",
  ombox: "ff",
  "ombox-content": "fg",
  "ombox-delete": "fh",
  "ombox-move": "fi",
  "ombox-notice": "fj",
  "ombox-protection": "fk",
  "ombox-speedy": "fl",
  "ombox-style": "fm",
  "page-Main_Page": "fn",
  "parsoid-body": "fo",
  patrollink: "fp",
  "permissions-errors": "fq",
  placeholder: "fr",
  plainlinks: "fs",
  "play-btn-large": "ft",
  PopUpMediaTransform: "fu",
  portal: "fv",
  "portal-column-right-extra-narrow": "fw",
  previewnote: "fx",
  printfooter: "fy",
  printonly: "fz",
  refbegin: "ga",
  "refbegin-100": "gb",
  reference: "gc",
  references: "gd",
  reflist: "ge",
  rtl: "gf",
  selected: "gg",
  selflink: "gh",
  sisterproject: "gi",
  "skin-vector": "gj",
  small: "gk",
  "small-talk": "gl",
  sortkey: "gm",
  "standard-talk": "gn",
  stub: "go",
  subpages: "gp",
  success: "gq",
  successbox: "gr",
  templatequote: "gs",
  templatequotecite: "gt",
  tex: "gu",
  texhtml: "gv",
  thumb: "gw",
  thumbborder: "gx",
  thumbcaption: "gy",
  thumbimage: "gz",
  thumbinner: "ha",
  tleft: "hb",
  tmbox: "hc",
  "tmbox-content": "hd",
  "tmbox-delete": "he",
  "tmbox-move": "hf",
  "tmbox-notice": "hg",
  "tmbox-speedy": "hh",
  "tmbox-style": "hi",
  toc: "hj",
  toccolours: "hk",
  tocnumber: "hl",
  toctext: "hm",
  toctitle: "hn",
  treeview: "ho",
  tright: "hp",
  "uls-settings-trigger": "hq",
  unpatrolled: "hr",
  updatedmarker: "hs",
  "user-block": "ht",
  usermessage: "hu",
  "ve-not-available": "hv",
  "ve-ui-mwNoticesPopupTool-item": "hw",
  vectorMenu: "hx",
  vectorTabs: "hy",
  visualClear: "hz",
  warning: "ia",
  warningbox: "ib",
  "wikiEditor-ui-clear": "ic",
  wikitable: "id",
  wpb: "ie",
  "wpb-header": "if",
  "wpb-outside": "ig",
  "wpbs-inner": "ih",
  "xdebug-error": "ii",
  noprint: "ij", // Everything here and below are custom
  nowrap: "ik",
  "mw-headline": "il",
  "mw-hiero-table": "im",
  "mw-jump": "in",
  "mw-normal-catlinks": "io",
  noviewer: "ip",
  "nv-edit": "iq",
  "nv-talk": "ir",
  "nv-view": "is",
  "reference-accessdate": "it",
  "reference-text": "iu",
  uid: "iv",
  visualhide: "iw",
  Z3988: "ix"
};

module.exports = {
  loadListFile,
  cleanUrl,
  getFilename,
  cleanListOfLinks,
  cssIds,
  cssClasses
};
